apiVersion: v1
kind: Pod
metadata:
  name: emotion-detection
  labels:
    app: emotion-service
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: bookapi
    image: emotion_detection:latest
    ports:
      - containerPort: 5000
    imagePullPolicy: Never
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: emotion-service
  labels:
    app: zbio-sample-googlebookapi
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: emotion-service
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    nodePort: 30045
