apiVersion: v1
kind: Pod
metadata:
  name: webcamapi
  labels:
    app: webcamapi
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: webcamapi
    image: webcam:v1
    env:
    - name: EMOTION_SERVICE
      value: "emotion-service:5000"
    ports:
      - containerPort: 80
    imagePullPolicy: Never
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0
---
kind: Service 
apiVersion: v1
metadata:
  name: webcamapi
  labels:
    app: webcamapi
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: webcamapi
  ports:
  - name: tcp
    port: 80
    targetPort: 80
    nodePort: 30046