FROM node:10-alpine as builder
WORKDIR /webcam
# copy the package.json to install dependencies
COPY package.json package-lock.json ./
# Install the dependencies and make the folder
RUN npm install
COPY . .
# Build the project and copy the files
RUN npm run ng build --prod
FROM nginx:alpine

# Copy from the stahg 1
COPY --from=builder /webcam/dist/webcam /usr/share/nginx/html
EXPOSE 4200 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]